on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    - release/*
    paths:
    - .github/workflows/test.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 51 23 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci

  Checkout:
     name: Checkout
     runs-on: ubuntu-20.04
     uses: actions/checkout@v4.2.2
    
  Python-up:
    name: Set Setup Python
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-python@v5.3.0
    with:
          python-version: '3.8'  # Укажите нужную версию Python
  Run-unit-tests: 
    runs-on: ubuntu-22.04
    steps:
    - name: Run unit tests
    - run: |
          python manage.py test  # Запуск тестов Django      
  
  Testing:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2

        - name: Run pytest (pytest-django)
          env:
            PYTHONPATH: webapp/src/
          uses: samwlms/pytest-django-action@1.9
          with:
            args: pytest --ds=webapp.settings_prod -o python_files=tests.py -o django_find_project=false
       
# Статический анализ безопасности с помощью Checkov GitHub Action
  Checkov:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.8
         uses: actions/setup-python@v4
         with:
           python-version: 3.8
       - name: Test with Checkov
         id: checkov
         uses: bridgecrewio/checkov-action@master
         with:
          directory: example/examplea
          framework: terraform 
 
