on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    - release/*
    paths:
    - .github/workflows/test.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 51 23 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci

    - name: Checkout
    - uses: actions/checkout@v4.2.2
    

    - name: Set Setup Python
    - uses: actions/setup-python@v5.3.0
    - with:
          python-version: '3.8'  # Укажите нужную версию Python

    - name: Install dependencies
    - run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Убедитесь, что у вас есть файл requirements.txt

    - name: Run unit tests
    - run: 
          python manage.py test  # Запуск тестов Django

    - name: Run unit tests
    - run: |
          python manage.py test  # Запуск тестов Django

      # Статический анализ безопасности с помощью Snyk
    - name: Run Snyk to check for vulnerabilities
    - uses: snyk/actions/python@v1
    - with:
          args: test
    - env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run OWASP ZAP - Security Scan
    - id: zap_scan
    - uses: zaproxy/action-full-scan@v0.1.0
    - with:
          target: 'http://your-application-url'  # Замените на URL вашего приложения
    - env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}  # Убедитесь, что вы создали секрет для вашего API-ключа ZAP
